import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline } from "@mui/material";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task management app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{height: "100vh"}}>
      <CssBaseline />
      <Toaster position="top-right"/>
        {children}
        </body>
    </html>
  );
}
